kind: pipeline
name: default

workspace:
  base: /book
  path: PanBook

steps:
- name: build
  image: docker:18.09-git
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - export TAG=`git describe --tags --exact-match 2> /dev/null || git rev-parse --short HEAD`
  - docker build -t panbook:$TAG .
  - docker tag panbook:$TAG panbook:latest

- name: doc-ctexbook
  image: panbook:latest
  pull: if-not-exists
  commands:
  - CJK="" DEBUG="-d" make ctex
  depends_on:
  - build

- name: doc-ctexbook-6inch
  image: panbook:latest
  pull: if-not-exists
  commands:
  - CJK="" DEBUG="-d" make ctex6in
  depends_on:
  - build
  - doc-ctexbook

- name: doc-elegantbook
  image: panbook:latest
  pull: if-not-exists
  commands:
  - CJK="" DEBUG="-d" make elegantbook
  depends_on:
  - build
  - doc-ctexbook-6inch

- name: demo-article
  image: panbook:latest
  pull: if-not-exists
  commands:
  - cd demo/article
  - DEBUG=-d make build
  depends_on:
  - build
  
- name: demo-slide
  image: panbook:latest
  pull: if-not-exists
  commands:
  - cd demo/beamer
  - make all-theme
  depends_on:
  - build
  - demo-article

- name: demo-cv
  image: panbook:latest
  pull: if-not-exists
  commands:
  - cd demo/cv
  - make all
  depends_on:
  - build
  - demo-slide

- name: demo-thesis
  image: panbook:latest
  pull: if-not-exists
  commands:
  - cd demo/thesis
  - make all
  depends_on:
  - build
  - demo-slide

- name: publish-doc
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - doc-ctexbook
  - doc-ctexbook-6inch
  - doc-elegantbook

- name: publish-article
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: demo/article/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-article

- name: publish-slide
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: demo/beamer/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-slide  

- name: publish-cv
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: demo/cv/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-cv 

- name: publish-thesis
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: demo/thesis/build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - demo-thesis

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock