kind: pipeline
name: default

steps:
- name: build
  image: docker:18.09
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t panbook:latest .
  
volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock