kind: pipeline
name: default

workspace:
  base: /book
  path: PanBook

steps:
- name: build
  image: docker:18.09-git
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - export TAG=`git describe --tags --exact-match 2> /dev/null || git rev-parse --short HEAD`
  - docker build -t panbook:$TAG .
  - docker tag panbook:$TAG panbook:latest

- name: doc-ctexbook
  image: panbook:latest
  pull: if-not-exists
  commands:
  - CJK="" DEBUG="-d" make ctex
  depends_on:
  - build  
- name: doc-ctexbook-6inch
  image: panbook:latest
  pull: if-not-exists
  commands:
  - CJK="" DEBUG="-d" make ctex6in
  depends_on:
  - build
- name: doc-elegantbook
  image: panbook:latest
  pull: if-not-exists
  commands:
  - CJK="" DEBUG="-d" make elegantbook
  depends_on:
  - build

- name: demo-slide
  image: panbook:latest
  pull: if-not-exists
  commands:
  - cd demo/beamer
  - make run
  depends_on:
  - build

- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
  - src: build/*.pdf
  - dest: 172.17.0.1::panbook

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock